### ISSUE TITLE
Unable to upload by complex name

### ISSUE THREAD

**Issue by g4s8** [artipie/files-adapter#4]
This adapter is working fine when I upload a file by repository name via Artipie:
I created repository config `simple.yaml`:
```yaml
repo:
  type: file
  storage:
    type: fs
    path: /tmp/artipie/repos/simple
```
and uploaded a file using:
```bash
http PUT http PUT http://localhost:8080/simple (some data)
```

But if I try to upload by file name:
```bash
http PUT http://localhost:8080/simple/filename (some data)
```

It's failing with error:
```
APP RxComputationThreadPool-3 com.artipie.vertx.DummySubscriber: Error occurred: io.vertx.core.file.FileSystemException: java.nio.file.FileSystemException: /tmp/artipie/repos/simple/simple/qwe: Not a directory
```

We need to be able to save files by complex keys/paths, e.g. upload `reponame/one/two/three/file` should work.
